### ISSUE TITLE
Setup for Mac OS 10.9.5 does not work: fatal error: 'malloc.h' file not found

### ISSUE THREAD

**Issue by abolger** [danielfrg/word2vec#23]
When building from the cloned directory, running 
"python setup.py make install" results in the following:

```
>>gcc word2vec-c/word2vec.c -o bin/word2vec -lm -pthread -O3 -Wall -march=native -funroll-loops -Wno-unused-result -I/usr/include/malloc
>>gcc word2vec-c/word2phrase.c -o bin/word2phrase -lm -pthread -O3 -Wall -march=native -funroll-loops -Wno-unused-result -I/usr/include/malloc
>>gcc word2vec-c/distance.c -o bin/word2vec-distance -lm -pthread -O3 -Wall -march=native -funroll-loops -Wno-unused-result -I/usr/include/malloc
word2vec-c/distance.c:18:10: fatal error: 'malloc.h' file not found
```

The Google Code archive reports the same issue for the original source code because of where the Mac OS puts the "malloc" and "stdlib" files.  I will submit a patch once I get it working.

**Comment by abolger** [comment]
Okay, fixed. Can build on Mac OS X 10.9 now. Submitting pull request.

**Comment by danielfrg** [comment]
Fixed on #24. Thanks for the fix :)
